version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override host variables for docker network
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/basics
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: sync
          path: ./main.py
          target: /app/main.py
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_celery_worker
    command: celery -A app.workers.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      # Override host variables for docker network
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/basics
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: sync
          path: ./main.py
          target: /app/main.py
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

  db:
    image: postgres:15-alpine
    container_name: fastapi_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=basics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fastapi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
